src/main/java/se/diabol/jenkins/pipeline/domain/ManualStep.java
src/main/java/se/diabol/jenkins/pipeline/trigger/BPPManualTriggerResolver.java
src/main/java/se/diabol/jenkins/pipeline/trigger/ManualTriggerResolver.java
src/test/java/se/diabol/jenkins/pipeline/domain/ManualStepTest.java

If two manual triggers triggers same downstream job plugin cant handle that.

JENKINS-26282 fixes for multiple manual triggers

---

src/main/webapp/pipe.js

Hi,
Currently we have more than 20 pipelines and those changes made a difference in our Raspberry Pi.

faster code and jslint improvement.

---

.travis.yml
README.md
pom.xml
src/main/webapp/pipe.js
src/test/java/se/diabol/jenkins/pipeline/functionaltest/ConfigureJobPage.java
src/test/java/se/diabol/jenkins/pipeline/functionaltest/DeliveryPipelinePage.java
src/test/java/se/diabol/jenkins/pipeline/functionaltest/GuiFunctionalIT.java
src/test/java/se/diabol/jenkins/pipeline/functionaltest/NewJobPage.java

Adding a couple of integration tests

Integration tests

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/pipeline/domain/Component.java
src/main/webapp/pipe.js
src/test/java/se/diabol/jenkins/pipeline/functionaltest/GuiFunctionalIT.java
src/test/java/se/diabol/jenkins/pipeline/sort/LatestActivityComparatorTest.java
src/test/java/se/diabol/jenkins/pipeline/sort/NameComparatorTest.java

Fixing problem when firstJob is in a different folder than the view

JENKINS-22921 Folder fix

---

src/main/webapp/pipe.js

Fixed hardcoded url for getting image

JENKINS-22921 Fixed hardcoded url

---

src/main/java/se/diabol/jenkins/pipeline/util/ProjectUtil.java

Fixes issue:
https://issues.jenkins-ci.org/browse/JENKINS-28619

JENKINS-28619 Removal of warning message

---

src/main/webapp/pipe.js

Continuation - changed build trigger from GET to POST #112 

---

src/main/webapp/pipeline-common.css

To make behavior more intuitive.

Pointer cursor for rebuild and manual task

---

.travis.yml
pom.xml

Upgrade of coveralls-maven-plugin

Upgrade of coveralls-maven-plugin

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/pipeline/domain/Pipeline.java
src/main/java/se/diabol/jenkins/pipeline/domain/Route.java
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/configure-entries.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-showTotalBuildTime.html
src/main/webapp/pipe.js
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/PipelineTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/RouteTest.java

by calculating all possible routes in a pipeline, and pick the route with largest total duration value. Total duration value is the sum of durations of each task in that route.

JENKINS-22482: Show total build time

---

.travis.yml
license-config.xml
license-header.txt
pom.xml
src/main/java/se/diabol/jenkins/pipeline/domain/Route.java
src/test/java/se/diabol/jenkins/pipeline/domain/RouteTest.java

and added license header for a couple of files

Added check if license header exists in source files

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/pipeline/domain/Change.java
src/main/java/se/diabol/jenkins/pipeline/domain/Component.java
src/main/java/se/diabol/jenkins/pipeline/domain/ManualStep.java
src/main/java/se/diabol/jenkins/pipeline/domain/Pipeline.java
src/main/java/se/diabol/jenkins/pipeline/domain/Stage.java
src/main/java/se/diabol/jenkins/pipeline/domain/Task.java
src/main/java/se/diabol/jenkins/pipeline/domain/Trigger.java
src/main/java/se/diabol/jenkins/pipeline/domain/UserInfo.java
src/main/java/se/diabol/jenkins/pipeline/domain/status/promotion/PromotionStatusProvider.java
src/main/java/se/diabol/jenkins/pipeline/trigger/BPPManualTriggerResolver.java
src/main/java/se/diabol/jenkins/pipeline/util/BuildUtil.java
src/main/java/se/diabol/jenkins/pipeline/util/ProjectUtil.java
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/EdgeTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/TriggerTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/UserInfoTest.java
src/test/java/se/diabol/jenkins/pipeline/trigger/BPPManualTriggerTest.java

Added @SuppressWarnings("unchecked"), added @Supp…ressWarnings("unused") and fixed bug in equals in class UserInfo

Fixed deprecations

---

src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-noOfColumns.html

Better description of noOfColumns

JENKINS-29324 Better description of noOfColumns

---

src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/ComponentSpec/help-firstJob.html
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-noOfColumns.html
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-noOfPipelines.html
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-showAggregatedPipeline.html
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-sorting.html

I notice a few uses of mistaken grammar and corrected them.

Correct verbiage in some of the help text.

---

src/main/resources/se/diabol/jenkins/pipeline/PipelineVersionContributor/help-versionTemplate.html
src/main/resources/se/diabol/jenkins/pipeline/PipelineVersionContributor/help-versionTemplate.jelly
src/main/resources/se/diabol/jenkins/pipeline/PipelineVersionTokenMacro/help.jelly

* Added help for PIPELINE_VERSION macro
* Help for versionTemplate includes listing of macros available

Better help text for TokenMacro:s

---

src/test/java/se/diabol/jenkins/pipeline/domain/task/TaskTest.java

Added some more tests for the issue and the fix.

JENKINS-30170 Added more tests

---

pom.xml

Fix to enable Jacoco

---

src/main/java/se/diabol/jenkins/pipeline/domain/Stage.java
src/test/java/se/diabol/jenkins/pipeline/domain/PipelineTest.java

Please refer to https://issues.jenkins-ci.org/browse/JENKINS-31317

[JENKINS-31317] shows multiple stages per row in the delivery pipeline

---

src/main/webapp/pipe.js
src/main/webapp/pipeline-common.css

High can be too big only with old jenkins (without new UI). Also some small changes acording arrows.

JENKINS-31996 - Fix stage header high with new jenkins base

---

src/main/java/se/diabol/jenkins/pipeline/domain/results/TestResult.java
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/configure-entries.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/help-showTestResults.html
src/test/java/se/diabol/jenkins/pipeline/domain/results/TestResultTest.java

Use hudson.tasks.test.AbstractTestResultAction instead.

JENKINS-33965 Test result not shown for example TAP plugin

---

src/main/webapp/pipeline.css

Fix for Firefox and IE, the arrow lines move when scrolling the page, breaking the connections
Before in Firefox browser
After fix in Firefox browser
Before in IE browser
After fix in IE browser

JENKINS-33175 Fix for Firefox and IE, the arrow lines move when scrolling the page, breaking the connections

---

pom.xml
src/main/java/se/diabol/jenkins/pipeline/portlet/DeliveryPipelineViewPortlet.java
src/main/java/se/diabol/jenkins/pipeline/portlet/ReadOnlyDeliveryPipelineView.java
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/main.jelly
src/main/resources/se/diabol/jenkins/pipeline/portlet/DeliveryPipelineViewPortlet/config.groovy
src/main/resources/se/diabol/jenkins/pipeline/portlet/DeliveryPipelineViewPortlet/portlet.jelly
src/main/webapp/pipe.js
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java
src/test/java/se/diabol/jenkins/pipeline/portlet/DeliveryPipelineViewPortletTest.java
src/test/java/se/diabol/jenkins/pipeline/portlet/ReadOnlyDeliveryPipelineViewTest.java

JENKINS 25541 Added support for Dashboard View Portlet for Delivery Pipeline

---

pom.xml

New repo config in pom-file so we can release (hopefully)

new repo config in pom-file

---

src/main/webapp/pipe.js

Fixed a memory leaked caused by how jsplumb was initiated.

JENKINS-39856 fixed memory leak caused by jsplumb

---

pom.xml
src/main/resources/index.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/index.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/legend.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/main.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/newViewDetail.jelly
src/main/resources/se/diabol/jenkins/pipeline/PipelineProperty/config.jelly
src/main/resources/se/diabol/jenkins/pipeline/PipelineProperty/help-descriptionTemplate.jelly
src/main/resources/se/diabol/jenkins/pipeline/PipelineProperty/help-stageName.jelly
src/main/resources/se/diabol/jenkins/pipeline/PipelineProperty/help-taskName.jelly
src/main/resources/se/diabol/jenkins/pipeline/PipelineVersionContributor/config.jelly
src/main/resources/se/diabol/jenkins/pipeline/portlet/DeliveryPipelineViewPortlet/portlet.jelly
src/test/java/se/diabol/jenkins/pipeline/functionaltest/GuiFunctionalIT.java

* Update core dependency to 1.642.3
* Raised Java requirement to Java 7
* Upgrade Selenium version
* Upgraded Guava dependency
* Upgraded Cloudbees folder dependency

JENKINS-43352 Update to Java 7 and core dependency to 1.642.3

---

pom.xml
src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/pipeline/domain/Component.java
src/main/java/se/diabol/jenkins/pipeline/domain/Pipeline.java
src/main/java/se/diabol/jenkins/pipeline/domain/Stage.java
src/main/java/se/diabol/jenkins/pipeline/domain/task/Task.java
src/main/java/se/diabol/jenkins/pipeline/util/FullScreen.java
src/main/java/se/diabol/jenkins/workflow/WorkflowPipelineView.java
src/main/java/se/diabol/jenkins/workflow/model/Component.java
src/test/java/se/diabol/jenkins/pipeline/domain/ComponentTest.java
src/test/java/se/diabol/jenkins/pipeline/util/FullScreenTest.java

* Extract logic on whether a request requires full screen to a designated utility class
* Use com.google.common.base.MoreObjects instead of deprecated com.google.common.base.Objects

Code cleanup and refactoring

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/workflow/WorkflowPipelineView.java
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/configure-entries.jelly
src/main/resources/se/diabol/jenkins/workflow/WorkflowPipelineView/configure-entries.jelly
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java
src/test/java/se/diabol/jenkins/workflow/WorkflowPipelineViewTest.java

* Added configuration option to pipeline view configuration

JENKINS-35346 Preserve view descriptions

---

.travis.yml

* Speeds up builds in Travis CI

CI configuration: Cache dependencies

---

src/main/webapp/themes/overview/pipe-fullscreen.css
src/main/webapp/themes/overview/pipe.js
src/main/webapp/themes/overview/pipeline-common.css
src/main/webapp/themes/overview/pipeline-fullscreen.css
src/main/webapp/themes/overview/pipeline.css

* Replace overall tabular layout with normal divs and spans.
* Move several inline styles to css.
* Make overall style more compact.
JENKINS-45213: https://issues.jenkins-ci.org/browse/JENKINS-45213

JENKINS-45213 - Improve overview theme

---

src/main/webapp/pipe.js
src/main/webapp/themes/overview/pipe.js

Continuing my previous request (https://github.com/Diabol/delivery-pipeline-plugin/pull/260), I've made few changes:
Commit 1: applied consistent quotes for both JS files
Commit 2: reduced complexity of few functions by inverting conditions & moving some logic to the separate functions (this part will be continued in the next request if you don't mind)

Improved JS codestyle according to best practices: quotes, few functions' complexity

---

src/main/webapp/pipe.js
src/main/webapp/themes/overview/pipe.js

@patbos @pskumar448 Applying changes in [pull request 264](https://github.com/Diabol/delivery-pipeline-plugin/pull/264) for overview theme.

JENKINS-46160 Improve performance for overview theme when tab/window is not active

---

src/main/webapp/pipe.js
src/main/webapp/themes/overview/pipe.js

* Changed counterparts operator to equality (eslint rule eqeqeq);
* Reduced complexity by inverting some conditions;
* Fixed indentation near HTML parts;
* Added newlines to few HTML strings;
* Applied correct naming for few one-symbol indentificators (this task should be finished in the next pull request).

JS codestyle improvements: equality, indentation & etc.

---

src/main/java/se/diabol/jenkins/pipeline/CauseResolver.java
src/main/java/se/diabol/jenkins/pipeline/RelationshipResolver.java
src/main/java/se/diabol/jenkins/pipeline/domain/Pipeline.java
src/main/java/se/diabol/jenkins/pipeline/util/BuildUtil.java
src/main/java/se/diabol/jenkins/pipeline/util/ProjectUtil.java

* Addressed compiler javadocs warnings

Improve Javadoc

---

src/main/java/se/diabol/jenkins/pipeline/resolver/CoreCauseResolver.java
src/main/java/se/diabol/jenkins/pipeline/resolver/SubProjectRelationshipResolver.java
src/test/java/se/diabol/jenkins/pipeline/resolver/CoreCauseResolverTest.java

* Rename SCM label (source control management) to VCS (version control system)

JENKINS-54701 Support branch indexing/event as trigger cause

---

pom.xml
src/main/java/se/diabol/jenkins/pipeline/token/TokenUtils.java

Sorry I messed-up the master branch because of a merge.
This branch is a clean rebase other master

JENKINS-61056 / replaces #308
