Diabol/delivery-pipeline-plugin

src/main/java/se/diabol/jenkins/pipeline/util/ProjectUtil.java
src/test/java/se/diabol/jenkins/pipeline/util/ProjectUtilTest.java

If there is a project with downstream projects which eventually loops back to itself (cyclic projects), then it will throw a stack overflow exception. Instead we print a warning about the cyclic project, and do not add the downstream projects.

[FIXED JENKINS-27298] Prevent a stack overflow if a project eventually cycles back to itself.

---

src/main/java/se/diabol/jenkins/pipeline/util/ProjectUtil.java
src/test/java/se/diabol/jenkins/pipeline/util/ProjectUtilTest.java

This PR solves two problems:
- JENKINS-27270: Regexp should work on lower level jobs as well (i.e. jobs in a folder)
- JENKINS-27539: When jobs with the same basic name exist in different folders, and one of those jobs is used in a pipeline, computation is stopped with a null pointer exception

[JENKINS-27270][JENKINS-27539] Problems with folders

---

pom.xml

Remove xerces from artifact since it is not needed. Was included from the promoted-builds optional dependency.

Removed xerces from artifact

---

src/main/webapp/pipe.js

AbstractItem.getUrl() always return URL that ends with '/'.

Fix 405 Method Not Allowed when url contains //

---

src/main/java/se/diabol/jenkins/pipeline/domain/status/SimpleStatus.java
src/test/java/se/diabol/jenkins/pipeline/domain/status/SimpleStatusTest.java

Not sure why these test were passing before. 
But now I have added null checks to safeguard against tests which are not well isolated and are not mocking all their dependencies.

Fixed NPE in unit tests

---

README.md

Added documentation about how to run the latest released Delivery Pipeline Plugin in a Docker container after making the image available in Docker hub

Added documentation about how to run the latest DPP release in Docker

---

src/main/webapp/pipeline-common.css

Successful build should not show solid green background color in the default (non-fullscreen) view.
Reverted background color set in pipeline-common.css introduced in commit (SHA-1) bba6b4ac2e74048042b2648a58bc45b29c78c87b which seems to fix the problem.

JENKINS-28837 Successful build should not show solid green background color

---

src/main/java/se/diabol/jenkins/pipeline/domain/Change.java
src/main/webapp/pipe.js
src/test/java/se/diabol/jenkins/pipeline/domain/ChangeTest.java
src/test/java/se/diabol/jenkins/pipeline/test/ParentAwareSCM.java
src/test/javascript/pipe-test.js

Hi! 
Here, at ZeroTurnaround, we use this plugin as a main thing in our delivery process, so we want to contribute some changes from us which we already use :)
This one, in combination with plugins like JIRA ( https://wiki.jenkins-ci.org/display/JENKINS/JIRA+Plugin ) allows you replace issue ids in commit message with links to the tracker, which is really helpful for QA to analyze affected issues from changes.
There is a regression because now we can't allow change message to be a link (since it can have a links inside of it, as well as other html elements from annotators (but it's safe because Jenkins controls html in such places)). This regression was replaced by clickable commit id, so users will be able to open changes, but instead of clicking on message they will click on a hash. …

Use annotated commit message

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java

The cause list is immutable as described in the comments of
[JENKINS-33467](https://issues.jenkins-ci.org/browse/JENKINS-33467).

Fix JENKINS-33594: Rebuilding broken in Jenkins ver. 1.653

---

pom.xml
src/main/java/se/diabol/jenkins/pipeline/PipelineVersionContributor.java
src/test/java/se/diabol/jenkins/pipeline/PipelineVersionContributorTest.java
src/test/java/se/diabol/jenkins/pipeline/test/ParentAwareSCM.java

* Set pipeline version as a custom invisible action and use it for retrieval
* Still store pipeline version as a parameter for backwards compatibility
* Updated Jenkins plugin dependency version

JENKINS-34805 Set pipeline version as a custom invisible action and use it for retrieval

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java

In order to improve efficiency, modified getItems() method in DeliveryPipelineView to only return the jobs that are displayed in the pipeline view.

JENKINS-34196 Modified getItems() method to only return jobs from pipeline view

---

pom.xml

I have noticed that Travis tests regularly fail on what seems to be a memory shortage. Increasing test memory might help.

Raised XmX for JUnit tests.

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/pipeline/domain/Component.java
src/main/java/se/diabol/jenkins/pipeline/domain/Pipeline.java
src/test/java/se/diabol/jenkins/pipeline/PipelinePaginationTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/ComponentTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/PipelineTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/status/SimpleStatusTest.java
src/test/java/se/diabol/jenkins/pipeline/sort/LatestActivityComparatorTest.java
src/test/java/se/diabol/jenkins/pipeline/sort/NameComparatorTest.java

According to the current design after getting pipelines only component is getting created. As pagination can be implemented at component level previously I didn't change the flow of current design, but because of this it has shown impact on the performance where when having large number of historical builds.
So to fix this performance issue I have to change the current design of elements creation flow. Before creating the pipelines first created component and passed that component to the method createPipelineLatest to get the pipelines exactly required for selected page.

JENKINS 35507 Fixed pagination performance issue when having large number of historical builds

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/pipeline/domain/Pipeline.java
src/main/java/se/diabol/jenkins/pipeline/domain/UserInfo.java
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/PipelineTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/UserInfoTest.java
src/test/java/se/diabol/jenkins/pipeline/domain/status/SimpleStatusTest.java

Improvements:
- Prevent additional access to the change set by extracting contributors from already extracted changes
- Return `null` for `changes` and `contributors` if `showChanges` is enabled, preventing additional server-side operations

[JENKINS-35951] Performance improvements for loading changes

---

src/main/java/se/diabol/jenkins/pipeline/trigger/BPPManualTriggerResolver.java
src/test/java/se/diabol/jenkins/pipeline/trigger/BPPManualTriggerResolverTest.java

My pipelines were missing some manual triggers. This was caused by some jobs having multiple upstream projects. Only the first upstream project was being checked for a manual trigger.
This change checks all upstream projects for a manual trigger in isManualTrigger

[JENKINS-35683] Check all upstream projects for manual triggers

---

src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/ComponentSpec/config.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/RegExpSpec/config.jelly
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/configure-entries.jelly

Along with this "Delete" button position also moved to bottom instead of top corner and it is also not properly aligned with form.
This is my observation today and thought of submit the PR.
@tommysdk 
Go through this PR very small amount of fix, It may help some users who want to re-order the components or regular expression blocks.
At present there is no JIRA number for this. Let me know if this is ok I will create task in JIRA.

Manual ordering of the Components and Regular Expression in Configure screen using Drag n Drop of repeatable property.

---

src/main/java/se/diabol/jenkins/pipeline/sort/FailedJobComparator.java
src/test/java/se/diabol/jenkins/pipeline/DeliveryPipelineViewTest.java
src/test/java/se/diabol/jenkins/pipeline/PipelineVersionContributorTest.java
src/test/java/se/diabol/jenkins/pipeline/sort/FailedJobComparatorTest.java
src/test/java/se/diabol/jenkins/pipeline/sort/LatestActivityComparatorTest.java
src/test/java/se/diabol/jenkins/pipeline/test/PipelineUtil.java

Added comparator that sorts pipelines with status failed first, and then by how recently they where run.

Jenkins 39614 add sort by failure

---

src/main/java/se/diabol/jenkins/pipeline/token/TokenUtils.java
src/test/java/se/diabol/jenkins/pipeline/token/TokenUtilsTest.java

* Provided a more fine grained error message with stacktrace
* A non-expanded string will make it more obvious that expansion failed
* Will correctly display delivery pipeline task names which has no expandable variables in the delivery pipeline view instead of defaulting to job name

JENKINS-40763 Return a non-expanded string template if the token-macro plugin fails with a MacroEvaluationException

---

src/main/webapp/pipe.js
src/main/webapp/themes/contrast/pipeline-common.css
src/main/webapp/themes/default/pipeline-common.css
src/main/webapp/themes/overview/pipe.js
src/main/webapp/themes/overview/pipeline-common.css

Fixed the issue, pagination div is not going to render when disabled and also fixed style sheets not to occupy the space when empty pagination div rendered.

JENKINS-42850 Fixed Pagination DIV being rendered even when paging is disabled

---

README.md

The link to the delivery pipeline plugin on the Jenkins Jira is broken, this will make it point to the closest equivalent I could find without knowing what the previous page looked like

Fix Jira issue URL in readme

---

src/main/webapp/pipe.js
src/main/webapp/themes/overview/pipe.js

Each step of this change will makes code a little bit more consistent, changes difference
will have less size and logical problems could be revealed easier.
Commit 1: variables declaration
Commit 2: indentation
Next steps will be performed in the scope of other pull requests. In further request I want to reduce overall complexity of JS code and find logical problems if they are available.

Improved JS codestyle according to best practices

---

src/main/java/se/diabol/jenkins/pipeline/DeliveryPipelineView.java
src/main/java/se/diabol/jenkins/workflow/WorkflowPipelineView.java
src/main/resources/se/diabol/jenkins/pipeline/DeliveryPipelineView/configure-entries.jelly
src/main/resources/se/diabol/jenkins/workflow/WorkflowPipelineView/configure-entries.jelly

As there is change in Select box scripts of Jenkins core, when used direct select tag instead of the Jelly form f:select it is showing 404 error below to the select box while configuring view
In this PR changed to f:select and filling options using the Descriptor method.

[JENKINS-46249] Fixed 404 Error while configuring Delivery Pipeline view

---

src/main/java/se/diabol/jenkins/workflow/WorkflowApi.java
src/main/java/se/diabol/jenkins/workflow/WorkflowPipelineView.java
src/main/java/se/diabol/jenkins/workflow/model/Pipeline.java
src/main/java/se/diabol/jenkins/workflow/model/Stage.java
src/main/java/se/diabol/jenkins/workflow/model/Task.java
src/main/java/se/diabol/jenkins/workflow/util/Name.java
src/test/java/se/diabol/jenkins/pipeline/workflow/PipelineTest.java
src/test/java/se/diabol/jenkins/workflow/WorkflowApiTest.java
src/test/java/se/diabol/jenkins/workflow/util/NameTest.java

* Improved how full job names are resolved
* Fixes broken links that occurs under some circumstances when using nested structures
* Refactored WorkflowApi to use WorkflowJob objects instead of strings for simplified usage

JENKINS-47408 Link directly to the corresponding pipeline run for Jenkins pipelines

---

pom.xml

There was a plugin installation error when we run the project. Test scope parameter removed from artifactId:workflow-basic-step dependency in pom.xml.

test scope removed from dependency artifactId:workflow-basic-steps

---

src/main/java/se/diabol/jenkins/pipeline/EnvVersionTokenMacro.java
src/main/java/se/diabol/jenkins/pipeline/PipelineVersionContributor.java
src/main/java/se/diabol/jenkins/pipeline/PipelineVersionTokenMacro.java
src/test/java/se/diabol/jenkins/pipeline/PipelineVersionContributorTest.java

* Affects usage of pipeline version generation in DeliveryPipelineView based views
* Remove usage of ParametersAction - essentially there for backwards compatability with Delivery Pipeline plugin 0.9.9 and older which with this code change is no longer supported

JENKINS-38062 Remove unsafe ParametersAction usage warnings

---

checkstyle-rules.xml
pom.xml
src/main/java/se/diabol/jenkins/pipeline/domain/status/promotion/PromotionStatus.java

Update Checkstyle dependency to avoid pulling in external DTDs. Remove a rule that's in violation of the baked-in DTD, and fix a whitespace rule violation that offends the update version.
This fix can alternatively be rebased onto the pending jdk11 branch.

Update checkstyle tool version, remove invalid rule, fix rule violation.

---

src/main/webapp/pipe.js

The duration of the promotion was displayed as NaN because an undefined property was referenced.

JENKINS-58332 Fix broken promotion duration display

---

.travis.yml
pom.xml

include the missing dependency with the latest version of the Joda TimeDate

JENKINS-60658

---

src/main/java/se/diabol/jenkins/workflow/WorkflowPipelineView.java

The `@DataBoundSetter` annotations are needed to allow the Job DSL and Configuration as Code plugins to create and configure pipeline views.

JENKINS-59117 add @DataBoundSetter annotations
